### ISSUE TITLE
npm run package: Not working?

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt-microbit-electron#11]
Edit:
Solutions within:
latest https://github.com/Microsoft/pxt-microbit-electron/issues/11#issuecomment-257110955 , but the truer solution lies in packaging as I found out
packaging has an error in the way node_modules is handled https://github.com/Microsoft/pxt-microbit-electron/issues/11#issuecomment-257114801

---

Is npm run package working?

I have the following from my quick test which I will investigate.

```
C:\Users\owen\pxt-microbit-electron>npm run package

> code-the-microbit@1.0.0 package C:\Users\owen\pxt-microbit-electron
> node ./dev_tools/package.js

Packaging app for platform win32 x64 using electron v1.4.4
Generated the following packaged apps:
    C:\Users\owen\pxt-microbit-electron\built\code-the-microbit-win32-x64

C:\Users\owen\pxt-microbit-electron>npm start

> code-the-microbit@1.0.0 start C:\Users\owen\pxt-microbit-electron
> electron .


Using PXT/microbit from C:\Users\owen\pxt-microbit-electron\node_modules\pxt-microbit with build engine yotta.
Going to C:\Users\owen\pxt-microbit-electron\node_modules\pxt-microbit
Starting server in C:\Users\owen\pxt-microbit-electron\node_modules\pxt-microbit
With pxt core at C:\Users\owen\pxt-microbit-electron\node_modules\pxt-core
serial: monitoring ports...
starting local ws server at 3233...
serial: failed to load, skipping...
---------------------------------------------

To launch the editor, open this URL:
http://localhost:3232/#local_token=55bc0701-c110-4da7-6e9b-37ca0f188ce7

---------------------------------------------
ws connection at /55bc0701-c110-4da7-6e9b-37ca0f188ce7/serial
offline HEX not found: C:\Users\owen\pxt-microbit-electron\node_modules\pxt-microbit\hexcache\d107f967df56733675cd2c37a3c19e28dfb79afa20f31eb62539074734d4d0c7.hex
cannot find any drives to deploy to
cannot find any drives to deploy to
cannot find any drives to deploy to
ws connection closed
ws connection at /55bc0701-c110-4da7-6e9b-37ca0f188ce7/serial
offline HEX not found: C:\Users\owen\pxt-microbit-electron\node_modules\pxt-microbit\hexcache\d107f967df56733675cd2c37a3c19e28dfb79afa20f31eb62539074734d4d0c7.hex

C:\Users\owen\pxt-microbit-electron>dir
 Volume in drive C has no label.
 Volume Serial Number is 0EE0-492B

 Directory of C:\Users\owen\pxt-microbit-electron

28-10-2016  13:59    <DIR>          .
28-10-2016  13:59    <DIR>          ..
28-10-2016  08:41                44 .gitignore
28-10-2016  08:41    <DIR>          .vscode
28-10-2016  13:59    <DIR>          built
28-10-2016  08:41    <DIR>          dev_tools
28-10-2016  08:41               411 index.html
28-10-2016  08:41               886 main.js
28-10-2016  13:58    <DIR>          node_modules
28-10-2016  10:44               706 package.json
28-10-2016  08:41             3.664 README.md
               5 File(s)          5.711 bytes
               6 Dir(s)  56.628.097.024 bytes free

C:\Users\owen\pxt-microbit-electron>cd built

C:\Users\owen\pxt-microbit-electron\built>dir
 Volume in drive C has no label.
 Volume Serial Number is 0EE0-492B

 Directory of C:\Users\owen\pxt-microbit-electron\built

28-10-2016  13:59    <DIR>          .
28-10-2016  13:59    <DIR>          ..
28-10-2016  13:59    <DIR>          code-the-microbit-win32-x64
               0 File(s)              0 bytes
               3 Dir(s)  56.627.499.008 bytes free

C:\Users\owen\pxt-microbit-electron\built>cd code-the-microbit-win32-x64

C:\Users\owen\pxt-microbit-electron\built\code-the-microbit-win32-x64>dir
 Volume in drive C has no label.
 Volume Serial Number is 0EE0-492B

 Directory of C:\Users\owen\pxt-microbit-electron\built\code-the-microbit-win32-x64

28-10-2016  13:59    <DIR>          .
28-10-2016  13:59    <DIR>          ..
28-10-2016  13:59            56.229 blink_image_resources_200_percent.pak
28-10-2016  13:59        88.017.408 code-the-microbit.exe
28-10-2016  13:59                15 content_resources_200_percent.pak
28-10-2016  13:59         9.849.199 content_shell.pak
28-10-2016  13:59         4.173.928 d3dcompiler_47.dll
28-10-2016  13:59         2.259.968 ffmpeg.dll
28-10-2016  13:59        10.127.200 icudtl.dat
28-10-2016  13:59            95.232 libEGL.dll
28-10-2016  13:59         2.917.376 libGLESv2.dll
28-10-2016  13:59             1.075 LICENSE
28-10-2016  13:59         1.376.933 LICENSES.chromium.html
28-10-2016  13:59    <DIR>          locales
28-10-2016  13:59           367.250 natives_blob.bin
28-10-2016  13:59        16.697.344 node.dll
28-10-2016  13:59    <DIR>          resources
28-10-2016  13:59           815.532 snapshot_blob.bin
28-10-2016  13:59            84.220 ui_resources_200_percent.pak
28-10-2016  13:59                 6 version
28-10-2016  13:59            59.985 views_resources_200_percent.pak
28-10-2016  13:59           107.368 xinput1_3.dll
              18 File(s)    137.006.268 bytes
               4 Dir(s)  56.627.490.816 bytes free

C:\Users\owen\pxt-microbit-electron\built\code-the-microbit-win32-x64>code-the-microbit.exe

C:\Users\owen\pxt-microbit-electron\built\code-the-microbit-win32-x64>
INTERNAL ERROR: Error: ENOENT: no such file or directory, open 'C:\Users\owen\pxt-microbit-electron\built\code-the-microbit-win32-x64\node_modules\pxt-microbit\pxtarget.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:178:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:511:29)
    at readJson (C:\Users\owen\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\node_modules\pxt-core\built\nodeutil.js:128:26)
    at Object.getPxtTarget (C:\Users\owen\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\node_modules\pxt-core\built\nodeutil.js:137:15)
    at Object.mainCli (C:\Users\owen\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\node_modules\pxt-core\built\pxt.js:77254:24)
    at App.startServerAndCreateWindow (C:\Users\owen\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\main.js:10:7)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

I read the following, but gave a bad result:

> Remember to run `npm run rebuild-native` before packaging, and make sure the app is working by running `npm start`.

```
C:\Users\owen\pxt-microbit-electron>npm run rebuild-native

> code-the-microbit@1.0.0 rebuild-native C:\Users\owen\pxt-microbit-electron
> node ./dev_tools/rebuild-native.js

Detecting linked modules ("npm link")...
Cleaning known native modules...
    Cleaning C:\Users\owen\pxt-microbit-electron\node_modules\serialport\build\release
Rebuilding native modules...
    C:\Users\owen\pxt-microbit-electron\node_modules

> electron@1.4.4 postinstall C:\Users\owen\pxt-microbit-electron\node_modules\electron
> node install.js


> nslog@3.0.0 install C:\Users\owen\pxt-microbit-electron\node_modules\nslog
> node-gyp rebuild


C:\Users\owen\pxt-microbit-electron\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Users\owen\pxt-microbit-electron\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

npm WARN prefer global marked@0.3.6 should be installed with -g
gyp ERR! clean error
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\owen\pxt-microbit-electron\node_modules\nslog\build\Release\nslog.node'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 10.0.14931
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\owen\\pxt-microbit-electron\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\owen\pxt-microbit-electron\node_modules\nslog
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14931
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\owen\\pxt-microbit-electron\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=1.4.4" "--arch=x64" "--update-binary"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\owen\pxt-microbit-electron\node_modules\npm-debug.log

{ Error: Process exited with code: 1
    at ChildProcess.<anonymous> (C:\Users\owen\pxt-microbit-electron\node_modules\electron-rebuild\lib\spawn.js:55:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  stdout: '\n> electron@1.4.4 postinstall C:\\Users\\owen\\pxt-microbit-electron\\node_modules\\electron\n> node install.js\n\n\n> nslog@3.0.0 install C:\\Users\\owen\\pxt-microbit-electron\\node_modules\\nslog\n> node-gyp rebuild\n\n\r\nC:\\Users\\owen\\pxt-microbit-electron\\node_modules\\nslog>if not defined npm_config_node_gyp (node "C:\\Users\\owen\\pxt-microbit-electron\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js" rebuild )  else (node "" rebuild ) \r\n',
  stderr: 'npm WARN prefer global marked@0.3.6 should be installed with -g\ngyp ERR! clean error \ngyp ERR! stack Error: EPERM: operation not permitted, unlink \'C:\\Users\\owen\\pxt-microbit-electron\\node_modules\\nslog\\build\\Release\\nslog.node\'\ngyp ERR! stack     at Error (native)\ngyp ERR! System Windows_NT 10.0.14931\ngyp ERR! command "C:\\\\Program Files\\\\nodejs\\\\node.exe" "C:\\\\Users\\\\owen\\\\pxt-microbit-electron\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js" "rebuild"\ngyp ERR! cwd C:\\Users\\owen\\pxt-microbit-electron\\node_modules\\nslog\ngyp ERR! node -v v6.9.1\ngyp ERR! node-gyp -v v3.4.0\ngyp ERR! not ok \n\nnpm ERR! Windows_NT 10.0.14931\nnpm ERR! argv "C:\\\\Program Files\\\\nodejs\\\\node.exe" "C:\\\\Users\\\\owen\\\\pxt-microbit-electron\\\\node_modules\\\\npm\\\\bin\\\\npm-cli.js" "rebuild" "--runtime=electron" "--target=1.4.4" "--arch=x64" "--update-binary"\nnpm ERR! node v6.9.1\nnpm ERR! npm  v3.10.9\nnpm ERR! code ELIFECYCLE\nnpm ERR! nslog@3.0.0 install: `node-gyp rebuild`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the nslog@3.0.0 install script \'node-gyp rebuild\'.\nnpm ERR! Make sure you have the latest version of node.js and npm installed.\nnpm ERR! If you do, this is most likely a problem with the nslog package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     node-gyp rebuild\nnpm ERR! You can get information on how to open an issue for this project with:\nnpm ERR!     npm bugs nslog\nnpm ERR! Or if that isn\'t available, you can get their info via:\nnpm ERR!     npm owner ls nslog\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     C:\\Users\\owen\\pxt-microbit-electron\\node_modules\\npm-debug.log\n' }
Failed to rebuild some native modules, see above for details

```

**Comment by OwenBrotherwood** [comment]
Second attempt with changing packaging to latest seems to work.
```
"Testing"
  "dependencies": {
      "pxt-microbit": "latest",
      "pxt-core": "latest"
  },
  "devDependencies": {
      "electron": "latest",
      "electron-rebuild": "latest",
      "electron-packager": "latest",
      "rimraf": "latest"
  }
```

**Comment by pelikhan** [comment]
Magic!

**Comment by OwenBrotherwood** [comment]
One has to copy node_modules from resources\app to the same directory as the exe for the program to run.
Note:
As is, if one runs the exe from the root of the clone, it works as it finds a node_modules in current directory.

I try and find out how this stuff is packaged so as to reference the resources\app\node_modules

**Comment by OwenBrotherwood** [comment]
Problem is probably this https://github.com/Microsoft/pxt-microbit-electron/blob/d7d1248af5a84df6fb8027b1465e24b466ddd216/main.js#L7

**Comment by OwenBrotherwood** [comment]
A few fixes and suggestions will soon be available in a pull request.
In the meantime, https://github.com/Microsoft/pxt/issues/566, is causing some problems for a perfect solution as far as the pxt-microbit-electron app is concerned.
Work in progress

**Comment by OwenBrotherwood** [comment]
Closed as https://github.com/Microsoft/pxt-microbit-electron/pull/15 is as far as it can get in this repo.
Probable problem with pxt or interaction pxt and pxt-microbit-electron
