### ISSUE TITLE
running code-the-microbit.exe in own directory results in "Not found"

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt-microbit-electron#16]
running code-the-microbit.exe in anything other than the git clone directory results in "Not found".
"Work in progress" to find problem.
It is a good idea to let the browser start in the main.js to view how the ptx-microbit is running, remove when concentrating on electron part of the problem
Be aware that cache can sometimes indicate "it" works: allways try again

**Comment by OwenBrotherwood** [comment]
looks like "something" wants node_modules i cwd: I copied all the built over and Not found does not appear

**Comment by OwenBrotherwood** [comment]
https://github.com/Microsoft/pxt-microbit-electron/issues/16 :: Not found for electron app when running in own .exe directory is due to pxt repository

**Comment by OwenBrotherwood** [comment]
Current work in progress at own repo gives an exception now when not running in clone-d directory so the Not found does not come 
Working thru the problem
```
C:\Users\owen\Source\Repos\pxt-microbit-electron\built>
electron cwdPath:C:\Users\owen\Source\Repos\pxt-microbit-electron\built
electron appPath:C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app
electron processPath:C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64
INTERNAL ERROR: Error: ENOENT: no such file or directory, open 'C:\Users\owen\Source\Repos\pxt-microbit-electron\built\node_modules\pxt-microbit\pxtarget.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:178:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:511:29)
    at readJson (C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\node_modules\pxt-core\built\nodeutil.js:128:26)
    at Object.getPxtTarget (C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\node_modules\pxt-core\built\nodeutil.js:137:15)
    at Object.mainCli (C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\node_modules\pxt-core\built\pxt.js:77225:24)
    at App.startServerAndCreateWindow (C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\main.js:52:7)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

```

**Comment by OwenBrotherwood** [comment]
With current work in progress, there is a reference to pxt core at the wrong place:
> With pxt core at C:\Users\owen\Source\Repos\pxt-microbit-electron\built\node_modules\pxt-core
Not found is present at this time when not running in clone-d directory
```
C:\Users\owen\Source\Repos\pxt-microbit-electron\built>
electron:FIXME: It is still not possible to start exe in anything other than the clone-d directory
electron:FIXME: should not refer to this 'With pxt core at C:UsersowenSourceRepospxt-microbit-electron
ode_modulespxt-core'
electron:FIXME: exit not zero with close of window
electron:cwdPath:C:\Users\owen\Source\Repos\pxt-microbit-electron\built
electron:appPath:C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app
electron:processPath:C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64
Using PXT/microbit from C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\node_modules\pxt-microbit with build engine yotta.
Going to C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\node_modules\pxt-microbit
electron:baseurl:file://C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app/
electron:url:file://C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app/index.html?electron=1#local_token=55bc0701-c110-4da7-6e9b-37ca0f188ce7
Starting server in C:\Users\owen\Source\Repos\pxt-microbit-electron\built\code-the-microbit-win32-x64\resources\app\node_modules\pxt-microbit
With pxt core at C:\Users\owen\Source\Repos\pxt-microbit-electron\built\node_modules\pxt-core
serial: monitoring ports...
starting local ws server at 3233...
serial: failed to load, skipping...
---------------------------------------------

To launch the editor, open this URL:
http://localhost:3232/#local_token=55bc0701-c110-4da7-6e9b-37ca0f188ce7

---------------------------------------------

```

**Comment by OwenBrotherwood** [comment]
@guillaumejenkins : please check my repo at  https://github.com/OwenBrotherwood/pxt-microbit-electron/tree/packaging to see some work done (a lot) to get app in shape

**Comment by OwenBrotherwood** [comment]
I close this and if/when the pull request is processed, a better issue can be created if necessary
https://github.com/Microsoft/pxt-microbit-electron/pull/18
