### ISSUE TITLE
serialport or just "latest": INTERNAL ERROR: Error: "DLL could not be initialised"

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt-microbit-electron#9]
Edit:
Solutions within:
latest https://github.com/Microsoft/pxt-microbit-electron/issues/9#issuecomment-256873955

see also 

https://github.com/Microsoft/pxt/issues/581#issuecomment-256842083

---

Hi
Sorry for the danish text: DLL could not be initialised
INTERNAL ERROR: Error: Det lykkedes ikke at initialisere en DLL.

I will try and do more work on the problem but this _could_ be a heads up

Running Windows Home Insider Preview
Build 14931.rs_prerelease 160916-1700
```
C:\Users\owen\pxt-microbit-electron>npm start

> code-the-microbit@1.0.0 start C:\Users\owen\pxt-microbit-electron
> electron .


Using PXT/microbit from C:\Users\owen\pxt-microbit-electron\node_modules\pxt-microbit.
Going to C:\Users\owen\pxt-microbit-electron\node_modules\pxt-microbit
Starting server in C:\Users\owen\pxt-microbit-electron\node_modules\pxt-microbit
With pxt core at C:\Users\owen\pxt-microbit-electron\node_modules\pxt-core
serial: monitoring ports...
starting local ws server at 3233...
INTERNAL ERROR: Error: Det lykkedes ikke at initialisere en DLL.
\\?\C:\Users\owen\pxt-microbit-electron\node_modules\serialport\build\Release\serialport.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\owen\pxt-microbit-electron\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\owen\pxt-microbit-electron\node_modules\serialport\lib\bindings.js:3:35)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Windows_NT 10.0.14931
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! code-the-microbit@1.0.0 start: `electron .`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the code-the-microbit@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the code-the-microbit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs code-the-microbit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls code-the-microbit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\owen\pxt-microbit-electron\npm-debug.log

C:\Users\owen\pxt-microbit-electron>node --version
v6.9.1

C:\Users\owen\pxt-microbit-electron>npm --version
3.10.8
```

**Comment by OwenBrotherwood** [comment]
What can I do for a local fix to keep going with this app?

**Comment by OwenBrotherwood** [comment]
Work In Progress:
changing node_modules to latest for 
pxt-microbit
pxt-core
serialport
means I now have an app on my screen
![latest](https://cloud.githubusercontent.com/assets/866122/19801486/b9716d7e-9cff-11e6-967e-728a05036ce4.PNG)

**Comment by OwenBrotherwood** [comment]
Closed as "solved" in pull request https://github.com/Microsoft/pxt-microbit-electron/pull/15 if applied
